#!/bin/bash

OLD_IFS="$IFS"

for db in $(< ./mydbs.txt);do	
	echo "Database $db is processed "
	#mysql "$db" < creates.sql || {
	#	echo "Failed on database: $db " >&2
	#}
done

IFS="$OLD_IFS"

# Alternative (if names are guaranteed simple)




